version: '3'
services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    expose: 
      - 8000
    ports:
      - '8000:8000'
    restart: on-failure
    container_name: rover-api
    volumes:
      - /app/node_modules 
      - ./api:/app 
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - /app/node_modules
      - ./client:/app
    expose:
      - 3000
    ports:
      - 3000:3000
    stdin_open: true
    restart: on-failure
    container_name: rover-client
    depends_on: 
      - api